// This file contains classes (with possible wildcards) that the Compose Compiler will treat as stable.
// It allows us to define classes that are not part of our codebase without wrapping them in a stable class.
// For more information, check https://developer.android.com/jetpack/compose/performance/stability/fix#configuration-file

// We always use immutable classes for collections and dates
// java.time classes are immutable
java.time.LocalDate
java.time.LocalTime
java.time.LocalDateTime
java.time.OffsetDateTime
java.time.ZonedDateTime
java.time.Instant
java.time.Duration
java.time.Period
java.time.ZoneId

// kotlinx.datetime classes are immutable
kotlinx.datetime.Instant
kotlinx.datetime.LocalDate
kotlinx.datetime.LocalDateTime
kotlinx.datetime.LocalTime
kotlinx.datetime.DateTimePeriod
kotlinx.datetime.DateTimeUnit
kotlinx.datetime.TimeZone
kotlinx.datetime.Month
kotlinx.datetime.DayOfWeek
